os:
  - windows
  - linux
  - osx
language: shell

matrix:
  include:
    - name: 'windows python setup'
      os: windows
      env: PATH=$PY37PATH:$PATH
      before_install:
        - choco install python
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python get-pip.py
      install:
        - python -m pip install pyinstaller
        - python -m pip install .
      script:
        - pyinstaller -n druid src/druid/main.py
        - ./dist/druid/druid.exe
    - name: 'linux python setup'
      os: linux
      install:
        - python3 -m pip install pyinstaller
        - python3 -m pip install .
      script:
        - pyinstaller -n druid src/druid/main.py
        - ./dist/druid/druid
    - name: 'osx python setup'
      os: osx
      install:
        - python3 -m pip install pyinstaller
        - python3 -m pip install .
      script:
        - pyinstaller -n druid src/druid/main.py
        - ./dist/druid/druid
