os:
  - windows
  - linux
  - osx
language: script

env:
  global:
    - TRAVIS_PYTHON_VERSION="3.7"
    - PY37PATH=/c/Python37:/c/Python37/Scripts
    - PATH=$PY37PATH:$PATH

install:
  - python -m pip install --upgrade pip
  - pip install pyinstaller

script:
  - pyinstaller --onefile druid.py
  - sleep 1  # Allow pyinstaller to finish writing to stdout
  - ls -l dist
  - dist/hello.exe
