os:
  - windows
  - linux
  - osx
language: shell

env:
  global:
    - PY37PATH=/c/Python37:/c/Python37/Scripts

matrix:
  include:
    - name: 'windows python setup'
      os: windows
      env: PATH=$PY37PATH:$PATH
      before_install:
        - choco install python
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python get-pip.py
      install:
        - python -m pip install pyinstaller
        - python -m pip install .
      script:
        - python -m pyinstaller -n druid src/druid/main.py
        - ./dist/druid/druid.exe
    - name: 'linux python setup'
      os: linux
      before_install:
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python3 get-pip.py
      install:
        - python3 -m pip install pyinstaller
        - python3 -m pip install .
      script:
        - python3 -m pyinstaller -n druid src/druid/main.py
        - ./dist/druid/druid
    - name: 'osx python setup'
      os: osx
      before_install:
        - brew install python || brew upgrade python
      install:
        - python3 -m pip install pyinstaller
        - python3 -m pip install .
      script:
        - python3 -m pyinstaller -n druid src/druid/main.py
        - ./dist/druid/druid
