os:
  - windows
  - linux
  - osx
language: shell

env:
  global:
    - PY37PATH=/c/Python37:/c/Python37/Scripts

matrix:
  include:
    - name: 'windows python setup'
      os: windows
      env: PATH=$PY37PATH:$PATH
      before_install:
        - choco install python
        - choco install pip
        - alias python3=python
  include:
    - name: 'linux python setup'
      os: linux
      before_install:
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python3 get-pip-.py
  include:
    - name: 'osx python setup'
      os: osx
      before_install:
        - brew install python
        - alias pip=pip3

install:
  - pip install pyinstaller

script:
  - pyinstaller --onefile druid.py
  - sleep 1  # Allow pyinstaller to finish writing to stdout
  - ls -l dist
  - ./dist/druid
