os:
  - windows
  - linux
  - osx
language: shell

matrix:
  include:
    - name: 'windows python setup'
      os: windows
      env: PATH=$PY37PATH:$PATH
      before_install:
        - choco install python
      install:
        - pip install pyinstaller
        - pip install .
      script:
        - pyinstaller -n druid src/druid/main.py
        - dir ./dist/druid/druid.exe
    - name: 'linux python setup'
      os: linux
      language: python
      install:
        - pip3 install pyinstaller
        - pip3 install .
      script:
        - pyinstaller -n druid src/druid/main.py
        - ls ./dist/druid/druid
    - name: 'osx python setup'
      os: osx
      install:
        - pip3 install pyinstaller
        - pip3 install .
      script:
        - pyinstaller -n druid src/druid/main.py
        - ls ./dist/druid/druid
