[tool.poetry]
name = "druid"
version = "0.0.1"
description = "shell and script loader for the monome crow module"
authors = ["Brian Crabtree", "Trent Gill", "Monome community"]

[tool.poetry.dependencies]
python = "^3.5"
prompt-toolkit = "^2.0"
pyserial = "^3.4"
